server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true 
      
spring:
  mvc:
    view: 
      prefix: /WEB-INF/view/ 
      suffix: .jsp 
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul 
    driver-class-name: com.mysql.cj.jdbc.Driver 
    username: root 
    password: asd123 
  sql:
    init:
      schema-locations:
      - classpath:db/table.sql
  
  h2:
    console:
      enabled: true
  
  output:
    ansi:
      enabled: always
      
#mybatis 설정
mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml  
  configuration:
    map-underscore-to-camel-case: true 
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.apache.ibatis: DEBUG 
